name: "Maria - isort and black checks"
description: "GH action providing isort and black checks on changed files of PR"
branding:
  icon: circle
  color: gray-dark
outputs:
  output:
    description: "Passes if isort and black checks succeed"
runs:
  using: "docker"
  image: "Dockerfile"
